FROM ubuntu:latest

MAINTAINER Krunal Shah <krumasta@gmail.com>

RUN apt-get update && apt-get install -qy \
 apache2 \
 libxml2 \
 libxml2-dev \
 libxslt1-dev \
 libmagickwand-dev \
 openjdk-7-jdk \
 memcached \
 redis-server \
 curl